name: Update Database Manifest

# Trigger on every push to main
on:
  push:
    branches:
      - main

permissions:
  contents: write  # allow committing back to repo

jobs:
  rebuild-manifest:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code (with write creds)
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2. (Still need Node to run your script)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Run your manifest-generator script directly
      - name: Generate manifest.json
        run: node scripts/generate_manifest.js

      # 4. Commit and push the updated manifest
      - name: Commit manifest.json
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: update database manifest"
          add: database/manifest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

